"""
Django settings for mess_management project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-b(+l6%yrhr#)&h828qd38_jl3kqabsh+bp&@l70nmk+t@y!evt')

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Allowed hosts - includes Render domain
ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS', 
    'localhost,127.0.0.1,.onrender.com'
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for django-allauth
    
    # Our app MUST come before allauth to override templates
    'core',  # Our mess management app
    
    # Django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for django-allauth
]

ROOT_URLCONF = 'mess_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Required by allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mess_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Database Configuration - PostgreSQL for production, SQLite for development
import dj_database_url

if os.environ.get('DATABASE_URL'):
    # Use PostgreSQL in production (when DATABASE_URL is set)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,  # Connection pooling
            conn_health_checks=True,  # Health checks
        )
    }
else:
    # Use SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise static files storage for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Sites Framework (Required for django-allauth)
SITE_ID = 1

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of allauth
    'django.contrib.auth.backends.ModelBackend',
    # allauth specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Authentication URLs
LOGIN_URL = 'account_login'  # Using allauth login URL
LOGIN_REDIRECT_URL = 'dashboard'
ACCOUNT_SIGNUP_REDIRECT_URL = 'dashboard'  # Redirect to dashboard after signup
LOGOUT_REDIRECT_URL = 'role_selection'

# Django-allauth Configuration
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # Allow login with username OR email
ACCOUNT_EMAIL_REQUIRED = True  # Email is required for signup
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Email verification is optional
ACCOUNT_USERNAME_REQUIRED = False  # Username is optional (auto-generated from email if not provided)
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True  # Confirm password on signup
ACCOUNT_SESSION_REMEMBER = True  # Remember user session
ACCOUNT_UNIQUE_EMAIL = True  # Enforce unique emails

# Social Account Configuration
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatically create account on social login
SOCIALACCOUNT_QUERY_EMAIL = True  # Request email from social provider
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'  # Don't require email verification for social accounts

# Custom Authentication Backend for Role-Based Login
AUTHENTICATION_BACKENDS = [
    'core.auth_backends.RoleBasedAuthBackend',  # Custom backend for role checking
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth backend for email/username
]

# Custom Form for showing helpful error messages
ACCOUNT_FORMS = {
    'login': 'core.auth_forms.UserLoginForm',
}

# Custom Account Adapter for welcome emails and success messages
ACCOUNT_ADAPTER = 'core.account_adapter.CustomAccountAdapter'

# Enable HTML emails for allauth
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}

# Email Configuration - Real Gmail SMTP Sending
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'pawantripathi802@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'Mess Manager <{EMAIL_HOST_USER}>')
SERVER_EMAIL = EMAIL_HOST_USER

# Password Reset Settings
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour (in seconds)

# INSTRUCTIONS TO SET EMAIL PASSWORD:
# For local development, create a .env file (NOT committed to Git) with:
# EMAIL_HOST_PASSWORD=your-16-char-app-password
# 
# For production (Render), set environment variable in dashboard:
# EMAIL_HOST_PASSWORD=your-16-char-app-password
#
# To get Gmail App Password:
# 1. Go to: https://myaccount.google.com/security
# 2. Enable "2-Step Verification" if not already enabled
# 3. Click "App passwords" (under 2-Step Verification)
# 4. Select: Mail + Other (custom name: "Mess Manager")
# 5. Copy the 16-character password (remove spaces!)
# 6. Set it as environment variable (never commit to Git!)


# ==================== RAILWAY PRODUCTION SETTINGS ====================
# Production settings for Railway deployment

if 'RAILWAY_ENVIRONMENT' in os.environ:
    DEBUG = False
    
    # Use Railway's DATABASE_URL for production database
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=False  # Railway MySQL doesn't require SSL
        )
    }
    
    # Allowed hosts from environment variable
    allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', '')
    if allowed_hosts_str:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]
    
    # Static files configuration
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Security settings for production
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Update MIDDLEWARE to include WhiteNoise (insert after SecurityMiddleware)
    if 'whitenoise.middleware.WhiteNoiseMiddleware' not in MIDDLEWARE:
        MIDDLEWARE.insert(
            MIDDLEWARE.index('django.middleware.security.SecurityMiddleware') + 1,
            'whitenoise.middleware.WhiteNoiseMiddleware'
        )
