# Generated by Django 5.0 on 2026-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='admin_reply',
            field=models.TextField(blank=True, help_text="Admin's response to this message", null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
