# Generated by Django 5.0 on 2026-02-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_admin_reply_message_replied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user_reply',
            field=models.TextField(blank=True, help_text="User's response to admin reply", null=True),
        ),
    ]
