# Generated by Django 5.0 on 2026-02-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_user_replied_at_message_user_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('user', 'User Message'), ('system', 'System/Reminder')], default='user', help_text='Type of message', max_length=10),
        ),
    ]
