# Generated by Django 5.0 on 2026-02-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this meal plan', unique=True)),
                ('breakfast', models.TextField(blank=True, help_text='Breakfast menu', null=True)),
                ('lunch', models.TextField(blank=True, help_text='Lunch menu', null=True)),
                ('dinner', models.TextField(blank=True, help_text='Dinner menu', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='grocery',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Grocery', 'verbose_name_plural': 'Groceries'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-month_year', 'user__first_name'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='fixedexpense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fixedexpense',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='joining_date',
        ),
        migrations.AlterField(
            model_name='grocery',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('grains', 'Grains'), ('dairy', 'Dairy'), ('spices', 'Spices'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.CharField(help_text='e.g., 5 kg, 2 liters', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
