# Generated by Django 5.0 on 2026-02-03 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_dark_mode_userprofile_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messsettings',
            name='current_month_year',
        ),
        migrations.RemoveField(
            model_name='messsettings',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='messsettings',
            name='upi_id',
        ),
        migrations.AddField(
            model_name='messsettings',
            name='address',
            field=models.TextField(blank=True, help_text='Mess address'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='admin_upi_id',
            field=models.CharField(blank=True, help_text='Admin UPI ID for payments', max_length=100),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='allow_partial_payments',
            field=models.BooleanField(default=False, help_text='Allow users to make partial payments'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='allow_self_registration',
            field=models.BooleanField(default=False, help_text='Allow users to register themselves'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic backups'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='auto_email_reports',
            field=models.BooleanField(default=True, help_text='Auto-email reports to all users'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='auto_generate_monthly_report',
            field=models.BooleanField(default=True, help_text='Auto-generate monthly reports'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='backup_frequency_days',
            field=models.IntegerField(default=7, help_text='Backup frequency in days'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='billing_day',
            field=models.IntegerField(default=1, help_text='Day of month for billing (1-31)'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for inquiries', max_length=254),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messsettings',
            name='currency_symbol',
            field=models.CharField(default='₹', help_text='Currency symbol', max_length=5),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='data_retention_months',
            field=models.IntegerField(default=24, help_text='Months to retain old data'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', help_text='Date display format', max_length=20),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='default_monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default monthly fee amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='default_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', help_text='Default theme for new users', max_length=10),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='email_signature',
            field=models.TextField(blank=True, help_text='Email signature for automated emails'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='enable_activity_logging',
            field=models.BooleanField(default=True, help_text='Enable activity logging'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='final_reminder_days',
            field=models.IntegerField(default=1, help_text='Days before due date for final reminder'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='first_reminder_days',
            field=models.IntegerField(default=7, help_text='Days before due date for first reminder'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='grace_period_days',
            field=models.IntegerField(default=3, help_text='Grace period after due date'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='inactive_user_cleanup_days',
            field=models.IntegerField(default=90, help_text='Days before inactive users are flagged'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='include_grocery_details',
            field=models.BooleanField(default=True, help_text='Include grocery details in reports'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='include_payment_details',
            field=models.BooleanField(default=True, help_text='Include payment details in reports'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='late_payment_penalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late payment penalty (₹ or %)', max_digits=5),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='late_payment_penalty_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='lockout_duration_minutes',
            field=models.IntegerField(default=30, help_text='Account lockout duration'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='log_retention_days',
            field=models.IntegerField(default=90, help_text='Days to retain activity logs'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='max_login_attempts',
            field=models.IntegerField(default=5, help_text='Maximum login attempts before lockout'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='max_users_allowed',
            field=models.IntegerField(default=50, help_text='Maximum number of users allowed'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='mess_name',
            field=models.CharField(default='Mess Management System', max_length=200),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='min_password_length',
            field=models.IntegerField(default=8, help_text='Minimum password length'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='operating_hours',
            field=models.CharField(blank=True, help_text='Operating hours (e.g., 7 AM - 10 PM)', max_length=100),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='report_generation_day',
            field=models.IntegerField(default=1, help_text='Day of month to generate reports'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='require_admin_approval',
            field=models.BooleanField(default=True, help_text='Require admin approval for new users'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='require_strong_passwords',
            field=models.BooleanField(default=True, help_text='Require strong passwords'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='second_reminder_days',
            field=models.IntegerField(default=3, help_text='Days before due date for second reminder'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='send_overdue_reminders',
            field=models.BooleanField(default=True, help_text='Send reminders for overdue payments'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='session_timeout_minutes',
            field=models.IntegerField(default=60, help_text='Session timeout in minutes'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='smtp_configured',
            field=models.BooleanField(default=False, help_text='SMTP email is configured'),
        ),
        migrations.AddField(
            model_name='messsettings',
            name='time_zone',
            field=models.CharField(default='Asia/Kolkata', help_text='System timezone', max_length=50),
        ),
        migrations.AlterField(
            model_name='messsettings',
            name='upi_qr_code',
            field=models.ImageField(blank=True, help_text='UPI QR code image', null=True, upload_to='upi_qr/'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_payment_reminders', models.BooleanField(default=True, help_text='Receive payment reminder emails')),
                ('email_grocery_updates', models.BooleanField(default=True, help_text='Receive grocery update emails')),
                ('email_monthly_reports', models.BooleanField(default=True, help_text='Receive monthly report emails')),
                ('email_admin_messages', models.BooleanField(default=True, help_text='Receive admin message notifications')),
                ('show_phone_to_members', models.BooleanField(default=True, help_text='Show phone number to other members')),
                ('show_payment_status', models.BooleanField(default=True, help_text='Show payment status to other members')),
                ('dashboard_default_view', models.CharField(choices=[('current', 'Current Month'), ('all', 'All Time')], default='current', help_text='Default dashboard time range', max_length=20)),
                ('payment_history_months', models.IntegerField(default=6, help_text='Number of months to show in payment history')),
                ('preferred_upi_app', models.CharField(blank=True, help_text='Preferred UPI app (GPay, PhonePe, Paytm)', max_length=20)),
                ('saved_upi_ids', models.JSONField(blank=True, default=list, help_text='List of saved UPI IDs')),
                ('payment_reminder_days', models.IntegerField(default=3, help_text='Days before due date to receive reminder')),
                ('auto_download_receipt', models.BooleanField(default=True, help_text='Auto-download receipt on payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
